import type { Ad } from "@/lib/types";

export const mockMyAds: Ad[] = [
  {
    id: "my-ad-001",
    kind: "produk",
    title: "Rice Cooker Mini 1.5L Bekas Pakai Rapi",
    category: "Barang Baru & Bekas",
    priceLabel: "Rp 350.000",
    location: "Hay Asyir, Kairo",
    status: "Aktif",
    postedAt: "5 hari lalu",
    sellerName: "Kamu",
    sellerJoinedYear: 2023,
    sellerActiveAds: 3,
    whatsappNumber: "201012345002",
    description:
      "Rice cooker mini 1.5L masih berfungsi normal, dipakai kurang lebih 8 bulan karena pindah kos.",
    condition: "Bekas",
    deliveryMethod: "COD",
  },
  {
    id: "my-ad-002",
    kind: "jasa",
    title: "Jasa Terjemah Dokumen Arab-Indonesia",
    category: "Pendidikan",
    priceLabel: "Mulai Rp 50.000",
    location: "Nasr City, Kairo",
    status: "Terjual",
    postedAt: "2 minggu lalu",
    sellerName: "Kamu",
    sellerJoinedYear: 2023,
    sellerActiveAds: 3,
    whatsappNumber: "201012345002",
    description: "Menerima jasa terjemah dokumen resmi maupun akademik.",
    scope: "Online & tatap muka",
    estimatedDuration: "1-2 hari kerja",
  },
  {
    id: "my-ad-003",
    kind: "produk",
    title: "Buku Paket Nahwu Shorof Edisi Lengkap",
    category: "Pendidikan",
    priceLabel: "Rp 120.000",
    location: "Hay Sabi', Kairo",
    status: "Selesai",
    postedAt: "1 bulan lalu",
    sellerName: "Kamu",
    sellerJoinedYear: 2023,
    sellerActiveAds: 3,
    whatsappNumber: "201012345002",
    description: "Paket buku Nahwu Shorof lengkap, kondisi masih bagus.",
    condition: "Bekas",
    deliveryMethod: "COD",
  },
  {
    id: "my-ad-004",
    kind: "produk",
    title: "Kasur Lipat Busa Ukuran Single",
    category: "Barang Baru & Bekas",
    priceLabel: "Rp 450.000",
    location: "Nasr City, Kairo",
    status: "Kedaluwarsa",
    postedAt: "2 bulan lalu",
    sellerName: "Kamu",
    sellerJoinedYear: 2023,
    sellerActiveAds: 3,
    whatsappNumber: "201012345002",
    description: "Kasur lipat busa baru, belum pernah dipakai.",
    condition: "Baru",
    deliveryMethod: "Antar Jemput",
  },
  {
    id: "my-ad-005",
    kind: "jasa",
    title: "Desain Poster & Undangan Digital",
    category: "Kreatif & Digital",
    priceLabel: "Mulai Rp 75.000",
    location: "Online",
    status: "Ditutup",
    postedAt: "3 bulan lalu",
    sellerName: "Kamu",
    sellerJoinedYear: 2023,
    sellerActiveAds: 3,
    whatsappNumber: "201012345002",
    description: "Jasa desain poster acara, undangan digital, dan konten promosi.",
    scope: "Online",
    estimatedDuration: "2-3 hari kerja",
  },
];
