import type { Ad } from "@/lib/types";

export function getAdById(id: string): Ad | undefined {
  return mockAds.find((ad) => ad.id === id);
}

export interface SellerProfile {
  name: string;
  joinedYear: number;
  activeAdsCount: number;
  ads: Ad[];
}

export function getSellerProfile(sellerName: string): SellerProfile | undefined {
  const ads = mockAds.filter((ad) => ad.sellerName === sellerName);
  if (ads.length === 0) return undefined;

  return {
    name: sellerName,
    joinedYear: ads[0].sellerJoinedYear,
    activeAdsCount: ads[0].sellerActiveAds,
    ads,
  };
}

export const mockAds: Ad[] = [
  {
    id: "ad-001",
    kind: "jasa",
    featured: true,
    title: "Jasa Terjemah Dokumen Arab-Indonesia",
    category: "Pendidikan",
    priceLabel: "Mulai Rp 50.000",
    location: "Nasr City, Kairo",
    status: "Aktif",
    postedAt: "2 jam lalu",
    sellerName: "Ahmad Fauzan",
    sellerJoinedYear: 2022,
    sellerActiveAds: 3,
    whatsappNumber: "201012345001",
    description:
      "Menerima jasa terjemah dokumen resmi maupun akademik dari Bahasa Arab ke Indonesia dan sebaliknya. Berpengalaman menerjemahkan surat keterangan, ijazah, dan tugas kuliah. Hasil terjemahan rapi dan bisa direvisi sesuai kebutuhan.",
    scope: "Online & tatap muka",
    estimatedDuration: "1-2 hari kerja",
  },
  {
    id: "ad-002",
    kind: "produk",
    title: "Rice Cooker Mini 1.5L Bekas Pakai Rapi",
    category: "Barang Baru & Bekas",
    priceLabel: "Rp 350.000",
    location: "Hay Asyir, Kairo",
    status: "Aktif",
    postedAt: "5 jam lalu",
    sellerName: "Siti Nur Aini",
    sellerJoinedYear: 2023,
    sellerActiveAds: 1,
    whatsappNumber: "201012345002",
    description:
      "Rice cooker mini 1.5L masih berfungsi normal, dipakai kurang lebih 8 bulan karena pindah kos. Body dan panci dalam kondisi bersih, tidak ada penyok. Cocok untuk anak kos.",
    condition: "Bekas",
    deliveryMethod: "COD",
  },
  {
    id: "ad-003",
    kind: "produk",
    featured: true,
    title: "Katering Harian Menu Nusantara",
    category: "Makanan & Minuman",
    priceLabel: "Rp 25.000 / porsi",
    location: "Hay Asyir, Kairo",
    status: "Aktif",
    postedAt: "8 jam lalu",
    sellerName: "Dapur Rindu Kampung",
    sellerJoinedYear: 2021,
    sellerActiveAds: 2,
    whatsappNumber: "201012345003",
    description:
      "Menyediakan katering harian dengan menu rumahan khas Nusantara, ganti menu setiap hari. Bisa langganan mingguan atau bulanan. Pemesanan minimal H-1 sebelum jam makan.",
    condition: "Baru",
    deliveryMethod: "Antar Jemput",
  },
  {
    id: "ad-004",
    kind: "jasa",
    title: "Desain Poster & Undangan Digital",
    category: "Kreatif & Digital",
    priceLabel: "Mulai Rp 75.000",
    location: "Online",
    status: "Aktif",
    postedAt: "12 jam lalu",
    sellerName: "Kalam Studio",
    sellerJoinedYear: 2023,
    sellerActiveAds: 4,
    whatsappNumber: "201012345004",
    description:
      "Jasa desain poster acara, undangan digital, dan konten promosi organisasi. Termasuk 2x revisi dan file siap cetak/siap unggah. Portofolio bisa dilihat lewat WhatsApp.",
    scope: "Online",
    estimatedDuration: "2-3 hari kerja",
  },
  {
    id: "ad-005",
    kind: "jasa",
    featured: true,
    title: "Bantuan Pindahan & Angkut Barang",
    category: "Bantuan & Layanan Harian",
    priceLabel: "Mulai Rp 150.000",
    location: "Madinat Nasr, Kairo",
    status: "Aktif",
    postedAt: "1 hari lalu",
    sellerName: "Rizky Pratama",
    sellerJoinedYear: 2020,
    sellerActiveAds: 1,
    whatsappNumber: "201012345005",
    description:
      "Membantu proses pindahan kos, angkut barang berat, dan bongkar muat. Tersedia armada kecil untuk barang dalam jumlah banyak. Harga menyesuaikan jarak dan volume barang.",
    scope: "Area Kairo Raya",
    estimatedDuration: "Sesuai jadwal",
  },
  {
    id: "ad-006",
    kind: "produk",
    title: "Buku Paket Nahwu Shorof Edisi Lengkap",
    category: "Pendidikan",
    priceLabel: "Rp 120.000",
    location: "Hay Sabi', Kairo",
    status: "Aktif",
    postedAt: "1 hari lalu",
    sellerName: "Muhammad Ridho",
    sellerJoinedYear: 2019,
    sellerActiveAds: 2,
    whatsappNumber: "201012345006",
    description:
      "Paket buku Nahwu Shorof lengkap, kondisi masih bagus, sedikit coretan pensil di beberapa halaman. Cocok untuk mahasiswa baru yang butuh referensi dasar.",
    condition: "Bekas",
    deliveryMethod: "COD",
  },
  {
    id: "ad-007",
    kind: "produk",
    title: "Kasur Lipat Busa Ukuran Single",
    category: "Barang Baru & Bekas",
    priceLabel: "Rp 450.000",
    location: "Nasr City, Kairo",
    status: "Aktif",
    postedAt: "2 hari lalu",
    sellerName: "Fajar Nugraha",
    sellerJoinedYear: 2022,
    sellerActiveAds: 1,
    whatsappNumber: "201012345007",
    description:
      "Kasur lipat busa baru, belum pernah dipakai, masih tersegel plastik. Ukuran single, praktis untuk kamar kos yang tidak terlalu luas.",
    condition: "Baru",
    deliveryMethod: "Antar Jemput",
  },
  {
    id: "ad-008",
    kind: "jasa",
    title: "Les Privat Bahasa Inggris & TOEFL",
    category: "Pendidikan",
    priceLabel: "Mulai Rp 60.000 / sesi",
    location: "Online",
    status: "Aktif",
    postedAt: "2 hari lalu",
    sellerName: "Nadia Ayu",
    sellerJoinedYear: 2021,
    sellerActiveAds: 1,
    whatsappNumber: "201012345008",
    description:
      "Les privat Bahasa Inggris untuk persiapan TOEFL ITP maupun percakapan sehari-hari. Materi disesuaikan dengan level dan target skor masing-masing peserta.",
    scope: "Online",
    estimatedDuration: "60 menit / sesi",
  },
  {
    id: "ad-009",
    kind: "produk",
    featured: true,
    title: "Kopi Nusantara Bubuk 250gr",
    category: "Makanan & Minuman",
    priceLabel: "Rp 90.000",
    location: "Hay Asyir, Kairo",
    status: "Aktif",
    postedAt: "3 hari lalu",
    sellerName: "Toko Rempah Ibu",
    sellerJoinedYear: 2020,
    sellerActiveAds: 5,
    whatsappNumber: "201012345009",
    description:
      "Kopi bubuk asli Nusantara kemasan 250gr, dibawa langsung dari Indonesia. Cocok untuk yang kangen rasa kopi kampung halaman. Stok terbatas.",
    condition: "Baru",
    deliveryMethod: "COD",
  },
  {
    id: "ad-010",
    kind: "jasa",
    title: "Edit Video & Motion Graphic Konten Sosial Media",
    category: "Kreatif & Digital",
    priceLabel: "Mulai Rp 100.000",
    location: "Online",
    status: "Aktif",
    postedAt: "3 hari lalu",
    sellerName: "Bayu Kreatif",
    sellerJoinedYear: 2023,
    sellerActiveAds: 3,
    whatsappNumber: "201012345010",
    description:
      "Jasa edit video reels/TikTok dan motion graphic sederhana untuk kebutuhan konten sosial media organisasi maupun personal. Termasuk 1x revisi minor.",
    scope: "Online",
    estimatedDuration: "3-4 hari kerja",
  },
  {
    id: "ad-011",
    kind: "produk",
    featured: true,
    title: "Sepeda Lipat Second Terawat",
    category: "Barang Baru & Bekas",
    priceLabel: "Rp 1.200.000",
    location: "Madinat Nasr, Kairo",
    status: "Aktif",
    postedAt: "4 hari lalu",
    sellerName: "Hasan Albana",
    sellerJoinedYear: 2018,
    sellerActiveAds: 1,
    whatsappNumber: "201012345011",
    description:
      "Sepeda lipat kondisi terawat, rutin servis, ban dan rem masih bagus. Dijual karena mau pulang ke Indonesia. Bisa dicoba langsung sebelum deal.",
    condition: "Bekas",
    deliveryMethod: "COD",
  },
  {
    id: "ad-012",
    kind: "jasa",
    title: "Jasa Cukur Rambut Panggilan ke Kos",
    category: "Bantuan & Layanan Harian",
    priceLabel: "Rp 70.000",
    location: "Hay Sabi', Kairo",
    status: "Aktif",
    postedAt: "5 hari lalu",
    sellerName: "Barbershop Abu",
    sellerJoinedYear: 2022,
    sellerActiveAds: 1,
    whatsappNumber: "201012345012",
    description:
      "Jasa cukur rambut panggilan langsung ke kos, praktis tanpa perlu keluar. Model potongan menyesuaikan permintaan, bawa alat cukur sendiri yang bersih dan higienis.",
    scope: "Panggilan area Kairo",
    estimatedDuration: "30 menit",
  },
];
